import * as cdk from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as rds from "aws-cdk-lib/aws-rds";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import { Construct } from "constructs";

interface DatabaseStackProps extends cdk.StackProps {
  vpc: ec2.Vpc;
  dbSecurityGroup: ec2.SecurityGroup;
}

/**
 * Database stack: two separate RDS instances + DynamoDB tables.
 *
 * Architecture:
 *   - auth-db:   dedicated PostgreSQL 15 for the Auth service (users table)
 *   - stats-db:  dedicated PostgreSQL 15 for the Stats service (matches, match_players)
 *                Stats service is not yet implemented, but the DB is provisioned now.
 *   - MatchmakingTickets: DynamoDB for ephemeral matchmaking tickets (1h TTL)
 *   - GameSessions:       DynamoDB for active game sessions (2h TTL)
 *
 * RDS credentials are auto-generated by Secrets Manager and stored as:
 *   - tank-battle/auth-db   → contains host, port, username, password, dbname
 *   - tank-battle/stats-db  → same structure
 *
 * The ECS task definitions reference these secrets to inject DB_* env vars.
 */
export class DatabaseStack extends cdk.Stack {
  readonly authDbSecret: secretsmanager.ISecret;
  readonly statsDbSecret: secretsmanager.ISecret;
  readonly matchmakingTicketsTableName: string;
  readonly matchmakingSessionsTableName: string;

  constructor(scope: Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props);

    const privateSubnets = {
      subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
    };

    // ── Auth DB ────────────────────────────────────────────────────────────────
    const authDbSecret = new secretsmanager.Secret(this, "AuthDbSecret", {
      secretName: "tank-battle/auth-db",
      description: "Auth service RDS credentials",
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: "authuser" }),
        generateStringKey: "password",
        excludePunctuation: true,
        includeSpace: false,
      },
    });

    const authDb = new rds.DatabaseInstance(this, "AuthDb", {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_15,
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.MICRO
      ),
      credentials: rds.Credentials.fromSecret(authDbSecret),
      databaseName: "authdb",
      vpc: props.vpc,
      vpcSubnets: privateSubnets,
      securityGroups: [props.dbSecurityGroup],
      backupRetention: cdk.Duration.days(1),
      deletionProtection: false,      // allow cdk destroy in course project
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      multiAz: false,                 // cost savings for course project
    });

    this.authDbSecret = authDbSecret;

    // ── Stats DB (reserved — stats service not yet implemented) ────────────────
    const statsDbSecret = new secretsmanager.Secret(this, "StatsDbSecret", {
      secretName: "tank-battle/stats-db",
      description: "Stats service RDS credentials (service not yet implemented)",
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: "statsuser" }),
        generateStringKey: "password",
        excludePunctuation: true,
        includeSpace: false,
      },
    });

    const statsDb = new rds.DatabaseInstance(this, "StatsDb", {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_15,
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.MICRO
      ),
      credentials: rds.Credentials.fromSecret(statsDbSecret),
      databaseName: "statsdb",
      vpc: props.vpc,
      vpcSubnets: privateSubnets,
      securityGroups: [props.dbSecurityGroup],
      backupRetention: cdk.Duration.days(1),
      deletionProtection: false,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      multiAz: false,
    });

    this.statsDbSecret = statsDbSecret;

    // ── DynamoDB: MatchmakingTickets ──────────────────────────────────────────
    // Stores in-flight matchmaking tickets. TTL auto-deletes after 1 hour.
    const ticketsTable = new dynamodb.Table(this, "MatchmakingTickets", {
      tableName: "MatchmakingTickets",
      partitionKey: {
        name: "ticket_id",
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST, // no upfront cost
      timeToLiveAttribute: "expires_at",
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // ── DynamoDB: GameSessions ────────────────────────────────────────────────
    // Stores active game session connection info. TTL auto-deletes after 2 hours.
    const sessionsTable = new dynamodb.Table(this, "GameSessions", {
      tableName: "GameSessions",
      partitionKey: {
        name: "session_id",
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: "expires_at",
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    this.matchmakingTicketsTableName = ticketsTable.tableName;
    this.matchmakingSessionsTableName = sessionsTable.tableName;

    // ── Outputs ────────────────────────────────────────────────────────────────
    new cdk.CfnOutput(this, "AuthDbEndpoint", {
      value: authDb.dbInstanceEndpointAddress,
      description: "Auth RDS endpoint",
    });
    new cdk.CfnOutput(this, "StatsDbEndpoint", {
      value: statsDb.dbInstanceEndpointAddress,
      description: "Stats RDS endpoint",
    });
    new cdk.CfnOutput(this, "AuthDbSecretArn", {
      value: authDbSecret.secretArn,
      description: "ARN of auth DB credentials secret",
    });
  }
}
